### ISSUE TITLE
Could not initialize class NBTReflectionUtil in 1.21 Paper

### ISSUE THREAD

**Issue by jho5245** [tr7zw/Item-NBT-API#284]
NBTAPI version: item-nbt-api 2.13.0 (maven-shading)
Paper version: 1.21 build #2 

When updated to 1.21 and tried to use 'NBT.get()' method, it throws an ExceptionInInitializerError: Exception java.lang.NullPointerException

Full log:
java.lang.NoClassDefFoundError: Could not initialize class com.jho5245.cucumbery.util.shading.NBTReflectionUtil
        at Cucumbery-1.0-dev.jar/com.jho5245.cucumbery.util.shading.NBTCompound.getType(NBTCompound.java:1348) ~[Cucumbery-1.0-dev.jar:?]
        at Cucumbery-1.0-dev.jar/com.jho5245.cucumbery.util.shading.NBTCompound.getCompound(NBTCompound.java:786) ~[Cucumbery-1.0-dev.jar:?]
        at Cucumbery-1.0-dev.jar/com.jho5245.cucumbery.util.shading.NBTCompound.getCompound(NBTCompound.java:33) ~[Cucumbery-1.0-dev.jar:?]
        at Cucumbery-1.0-dev.jar/com.jho5245.cucumbery.util.nbt.NBTAPI.lambda$getMainCompound$0(NBTAPI.java:267) ~[Cucumbery-1.0-dev.jar:?]
        at Cucumbery-1.0-dev.jar/com.jho5245.cucumbery.util.shading.NBT.get(NBT.java:60) ~[Cucumbery-1.0-dev.jar:?]
        at Cucumbery-1.0-dev.jar/com.jho5245.cucumbery.util.nbt.NBTAPI.getMainCompound(NBTAPI.java:267) ~[Cucumbery-1.0-dev.jar:?]
        at Cucumbery-1.0-dev.jar/com.jho5245.cucumbery.listeners.inventory.InventoryMoveItem.onInventoryMoveItem(InventoryMoveItem.java:37) ~[Cucumbery-1.0-dev.jar:?]

**Comment by tr7zw** [comment]
Use the dev build 2.13.1-SNAPSHOT.

**Comment by gamingoninsulin** [comment]
how tohet that version i got  the same crash but i cant seem to find build 2.13.1-SNAPSHOT
